# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'AVKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AVKitDemo
  pod 'LYAVKit', :path => '../../'
end

target 'AVKitDemoTests' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AVKitDemo
  pod 'LYAVKit', :path => '../../'
end

